In [13]:
import pandas as pd
import glob

In [14]:
glob.glob('*.csv')

['y_train_smpl_0.csv',
 'y_train_smpl_1.csv',
 'y_train_smpl_3.csv',
 'x_train_gr_smpl.csv',
 'y_train_smpl_2.csv',
 'y_train_smpl_6.csv',
 'y_train_smpl_7.csv',
 'y_train_smpl.csv',
 'y_train_smpl_5.csv',
 'y_train_smpl_4.csv',
 'x_train_smpl_bin.csv',
 'y_train_smpl_9.csv',
 'y_train_smpl_8.csv']

In [15]:
TrainX = pd.read_csv("x_train_gr_smpl.csv")
TrainY0 = pd.read_csv('y_train_smpl_0.csv', names = ["y0"], header=0)
TrainY1 = pd.read_csv('y_train_smpl_1.csv', names = ["y1"], header=0)
TrainY2 = pd.read_csv('y_train_smpl_2.csv', names = ["y2"], header=0)
TrainY3 = pd.read_csv('y_train_smpl_3.csv', names = ["y3"], header=0)
TrainY4 = pd.read_csv('y_train_smpl_4.csv', names = ["y4"], header=0)
TrainY5 = pd.read_csv('y_train_smpl_5.csv', names = ["y5"], header=0)
TrainY6 = pd.read_csv('y_train_smpl_6.csv', names = ["y6"], header=0)
TrainY7 = pd.read_csv('y_train_smpl_7.csv', names = ["y7"], header=0)
TrainY8 = pd.read_csv('y_train_smpl_8.csv', names = ["y8"], header=0)
TrainY9 = pd.read_csv('y_train_smpl_9.csv', names = ["y9"], header=0)
TestX = pd.read_csv('x_train_smpl_bin.csv')
TrainY = pd.read_csv('y_train_smpl.csv', names = ["yALL"], header=0)

In [43]:
frames = [TrainX, TrainY]
randomdf = pd.concat(frames, axis=1).sample(frac=1)
TrainXRandom = randomdf.drop('yALL', axis=1)
TrainYRandom = randomdf['yALL']
randomdf.head()

0     1     2     3     4     5     6     7     8     9  ...   2295  \
1306  59.0  56.0  54.0  54.0  52.0  52.0  54.0  61.0  67.0  63.0  ...  128.0   
4073  41.0  40.0  56.0  64.0  61.0  56.0  58.0  63.0  75.0  88.0  ...   41.0   
97    19.0  20.0  22.0  22.0  23.0  23.0  26.0  29.0  33.0  32.0  ...  132.0   
6490  55.0  54.0  52.0  55.0  57.0  58.0  54.0  49.0  46.0  46.0  ...   21.0   
7294  42.0  43.0  45.0  42.0  40.0  40.0  39.0  37.0  37.0  39.0  ...   38.0   

       2296   2297   2298   2299   2300   2301   2302   2303  yALL  
1306   90.0   66.0   50.0   43.0   42.0   41.0   43.0   47.0     1  
4073   40.0   40.0   37.0   34.0   29.0   29.0   32.0   31.0     2  
97    134.0  135.0  137.0  138.0  141.0  142.0  126.0  112.0     0  
6490   22.0   23.0   25.0   26.0   26.0   24.0   23.0   23.0     4  
7294   39.0   38.0   39.0   44.0   42.0   37.0   34.0   33.0     4  

[5 rows x 2305 columns]

In [22]:
from sklearn.model_selection import train_test_split
X_train, X_test, Y_train, Y_test = train_test_split(TrainXRandom,TrainYRandom,test_size = 0.20)

In [23]:
from sklearn.naive_bayes import GaussianNB
model = GaussianNB()
model.fit(X_train, Y_train)

GaussianNB()

In [30]:
predictions = model.predict(X_test)

In [37]:
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score
print("Confusion Matrix:\n", confusion_matrix(Y_test, predictions))
print("Classification Report:\n", classification_report(Y_test, predictions))
print("Accuracy:", accuracy_score(Y_test, predictions))

Confusion Matrix:
 [[ 24   0   4   3   2   0   0   3   0   0]
 [ 99 107  49  12  33   3  75  70   1   4]
 [ 29  81  84  40  67   2  61  79   0  11]
 [  6  17   2  69  14   0 164  21   4   5]
 [ 13  39  36  17  71   1 167  35   0   4]
 [  3   1   1   0   0   5  14  23   1   0]
 [  0   1   0   0   0   0  36  12   0   9]
 [  0   0   2   1   0   0  16  21   1   2]
 [  1  12  10   0   0   4  27  21  22  12]
 [  0   2   0   0   2   0   1  34   0  13]]
Classification Report:
               precision    recall  f1-score   support

           0       0.14      0.67      0.23        36
           1       0.41      0.24      0.30       453
           2       0.45      0.19      0.26       454
           3       0.49      0.23      0.31       302
           4       0.38      0.19      0.25       383
           5       0.33      0.10      0.16        48
           6       0.06      0.62      0.12        58
           7       0.07      0.49      0.12        43
           8       0.76      0.20      

# Feature Selection

In [49]:
TrainX.head()

0     1     2     3     4      5      6      7      8      9  ...  \
0  78.0  77.0  76.0  82.0  87.0   92.0  104.0  119.0  117.0  120.0  ...   
1  73.0  75.0  79.0  78.0  76.0   75.0   89.0  107.0  133.0  125.0  ...   
2  72.0  75.0  79.0  77.0  81.0   89.0  105.0  109.0   86.0   90.0  ...   
3  67.0  70.0  74.0  80.0  93.0  107.0  110.0   96.0   69.0  100.0  ...   
4  74.0  74.0  73.0  72.0  77.0   87.0  104.0  109.0   84.0   83.0  ...   

    2294  2295  2296   2297  2298  2299  2300   2301   2302   2303  
0   87.0  79.0  72.0   76.0  83.0  95.0  99.0   98.0   95.0   94.0  
1   96.0  93.0  85.0   77.0  69.0  73.0  83.0  100.0  101.0  101.0  
2   98.0  95.0  88.0   80.0  73.0  71.0  74.0   80.0   89.0   95.0  
3  112.0  92.0  87.0   82.0  77.0  72.0  70.0   72.0   81.0   88.0  
4  100.0  98.0  99.0  100.0  99.0  89.0  78.0   66.0   68.0   72.0  

[5 rows x 2304 columns]

In [54]:
import numpy as np

TrainX_mean = np.mean(TrainX, axis=0)
TrainX_std = np.std(TrainX, axis=0)
TrainX_demean = TrainX - TrainX_mean
TrainX_normalize = TrainX_demean/TrainX_std
TrainX_normalize

0         1         2         3         4         5         6  \
0    -0.150399 -0.162027 -0.172519 -0.097642 -0.036323  0.027781  0.183140   
1    -0.214900 -0.187858 -0.133733 -0.149259 -0.178381 -0.192213 -0.011459   
2    -0.227801 -0.187858 -0.133733 -0.162163 -0.113809 -0.011042  0.196113   
3    -0.292303 -0.252435 -0.198377 -0.123451  0.041163  0.221892  0.260979   
4    -0.202000 -0.200774 -0.211306 -0.226683 -0.165466 -0.036923  0.183140   
...        ...       ...       ...       ...       ...       ...       ...   
9685  2.029759  1.684885  2.128814  1.592795  0.506080  1.528910  2.129126   
9686  0.791326  0.367507  2.128814  2.134767  2.133287  2.137127  2.129126   
9687  2.132961  2.136926  2.141743  2.134767  2.133287  2.137127  2.142099   
9688  2.132961  2.111095  2.141743  2.134767  2.133287  2.137127  2.142099   
9689  2.094260  1.284505  1.921953  2.134767  2.133287  2.007719  1.675062   

             7         8         9  ...      2294      2295      2296  \
0     0.376523  0.348175  0.382116  ...  0.225885  0.109520  0.009264   
1     0.220836  0.555810  0.446924  ...  0.363572  0.323470  0.208044   
2     0.246784 -0.054117 -0.006728  ...  0.394169  0.354035  0.253917   
3     0.078123 -0.274729  0.122887  ...  0.608349  0.308188  0.238626   
4     0.246784 -0.080071 -0.097459  ...  0.424766  0.399881  0.422115   
...        ...       ...       ...  ...       ...       ...       ...   
9685  2.140975  2.139025  2.131917  ... -0.569640 -0.654587 -0.678820   
9686  2.128001  2.126048  2.093032  ... -0.539043 -0.624022 -0.632948   
9687  2.140975  2.139025  2.131917  ... -0.477849 -0.348944 -0.449459   
9688  2.140975  2.139025  2.131917  ... -0.523744 -0.685151 -0.694111   
9689  1.583097  0.646650 -0.654802  ... -0.584938 -0.746280 -0.739983   

          2297      2298      2299      2300      2301      2302      2303  
0     0.083325  0.205600  0.404813  0.477748  0.472884  0.432761  0.418985  
1     0.098676 -0.010175  0.063870  0.228803  0.504234  0.527348  0.529216  
2     0.144730  0.051475  0.032876  0.088772  0.190735  0.338174  0.434732  
3     0.175433  0.113125  0.048373  0.026536  0.065335  0.212059  0.324501  
4     0.451757  0.452199  0.311828  0.151008 -0.028715  0.007121  0.072545  
...        ...       ...       ...       ...       ...       ...       ...  
9685 -0.684242 -0.688323 -0.710999 -0.720299 -0.655713 -0.654986 -0.636083  
9686 -0.622837 -0.611260 -0.602517 -0.611386 -0.655713 -0.623458 -0.636083  
9687 -0.530729 -0.565023 -0.509533 -0.455795 -0.577338 -0.450048 -0.384126  
9688 -0.668891 -0.534198 -0.633512 -0.642504 -0.655713 -0.654986 -0.683325  
9689 -0.622837 -0.580435 -0.710999 -0.704740 -0.655713 -0.749573 -0.793556  

[9690 rows x 2304 columns]

In [58]:
labels = [TrainY0, TrainY1, TrainY2, TrainY3, TrainY4, TrainY5, TrainY6, TrainY7, TrainY8, TrainY9]
labelsdf = pd.concat(labels, axis = 1)
labelsdf_normalize = (labelsdf - np.mean(labelsdf, axis=0))/np.std(labelsdf, axis=0)

In [59]:
labelsdf_normalize

y0       y1        y2        y3        y4        y5        y6  \
0    -6.718843  0.54515  0.549927  0.412662  0.506764  0.148835  0.196431   
1    -6.718843  0.54515  0.549927  0.412662  0.506764  0.148835  0.196431   
2    -6.718843  0.54515  0.549927  0.412662  0.506764  0.148835  0.196431   
3    -6.718843  0.54515  0.549927  0.412662  0.506764  0.148835  0.196431   
4    -6.718843  0.54515  0.549927  0.412662  0.506764  0.148835  0.196431   
...        ...      ...       ...       ...       ...       ...       ...   
9685  0.148835  0.54515  0.549927  0.412662  0.506764  0.148835  0.196431   
9686  0.148835  0.54515  0.549927  0.412662  0.506764  0.148835  0.196431   
9687  0.148835  0.54515  0.549927  0.412662  0.506764  0.148835  0.196431   
9688  0.148835  0.54515  0.549927  0.412662  0.506764  0.148835  0.196431   
9689  0.148835  0.54515  0.549927  0.412662  0.506764  0.148835  0.196431   

            y7        y8        y9  
0     0.159364  0.242933  0.169300  
1     0.159364  0.242933  0.169300  
2     0.159364  0.242933  0.169300  
3     0.159364  0.242933  0.169300  
4     0.159364  0.242933  0.169300  
...        ...       ...       ...  
9685  0.159364  0.242933 -5.906682  
9686  0.159364  0.242933 -5.906682  
9687  0.159364  0.242933 -5.906682  
9688  0.159364  0.242933 -5.906682  
9689  0.159364  0.242933 -5.906682  

[9690 rows x 10 columns]

In [87]:
correlation_Y2X = labelsdf_normalize.values.transpose().dot(TrainX_normalize.values)/(TrainX.shape[0]-1)
correlation_Y2X = np.abs(correlation_Y2X)

In [98]:
def correlated_feature_indexes(correlationY2X, top=1):
    return [np.argpartition(x_correlations, len(x_correlations)-top)[-top:]
            for x_correlations in correlationY2X]

top5_features = correlated_feature_indexes(correlation_Y2X, top=5)
top10_features = correlated_feature_indexes(correlation_Y2X, top=10)
top20_features = correlated_feature_indexes(correlation_Y2X, top=20)

In [103]:
top5_features_union = set([feature_index for label_set in top5_features for feature_index in label_set])
top10_features_union = set([feature_index for label_set in top10_features for feature_index in label_set])
top20_features_union = set([feature_index for label_set in top20_features for feature_index in label_set])

In [105]:
len(top5_features_union), len(top10_features_union), len(top20_features_union)

(45, 82, 148)

In [110]:
trainX_top50 = TrainXRandom.loc[:,[str(index) for index in top5_features_union]]

In [111]:
trainX_top50.head()

1666   1030   1031    792    793    794   1694   1695   1313   1316  \
1306  200.0  119.0  194.0  255.0  255.0  255.0  170.0  183.0  255.0  247.0   
4073   87.0   91.0   99.0  145.0  142.0  141.0   48.0   56.0  104.0  134.0   
97     64.0  115.0  103.0  143.0  147.0  149.0  113.0   95.0  135.0   93.0   
6490   36.0   47.0   47.0  109.0  107.0  104.0   39.0   38.0  121.0   81.0   
7294   69.0  151.0  148.0  198.0  209.0  215.0   41.0   41.0  114.0  226.0   

      ...   1121   1761   1507   1508   1134   1263   1265   1266   1268  \
1306  ...  255.0  187.0  114.0  110.0  255.0  255.0  255.0  252.0  216.0   
4073  ...   64.0   62.0   78.0  107.0  137.0  140.0   68.0   54.0   89.0   
97    ...  146.0   65.0  102.0  104.0  125.0  117.0  146.0  139.0  106.0   
6490  ...  105.0   44.0   89.0   89.0   77.0  119.0  121.0  123.0   91.0   
7294  ...  130.0   52.0   76.0  122.0  169.0   77.0  114.0  162.0  237.0   

       1269  
1306  149.0  
4073   82.0  
97    101.0  
6490   64.0  
7294  225.0  

[5 rows x 45 columns]